const dotenv = require("dotenv");
const connectDB = require("./config/db");
const Product = require("./models/Product");
const CartItem = require("./models/CartItem");
const WishlistItem = require("./models/WishlistItem");
const Order = require("./models/Order");

dotenv.config();

const products = [
  {
    name: "Relaxed Linen Shirt",
    brand: "Cloud Nine",
    category: "Clothing",
    gender: "All",
    price: 269000,
    originalPrice: 269000,
    stock: 36,
    rating: 4.2,
    soldCount: 434,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "White", "Navy"],
    tags: ["clothing", "cloud-nine", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/_S-VPVaegeVE6pY-F3hpinIvH18=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/gap-6037-3272525-1.jpg",
    description:
      "Relaxed Linen Shirt dari Cloud Nine dirancang dengan bahan terbaik. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk dipakai sehari hari. Jaminan belanja 100% sama dengan gambar.",
    material: "Cotton Blend",
  },
  {
    name: "Tailored Wide Pants",
    brand: "Hana Mode",
    category: "Clothing",
    gender: "Women",
    price: 239000,
    originalPrice: 239000,
    stock: 82,
    rating: 4.0,
    soldCount: 829,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "Navy", "Taupe"],
    tags: ["clothing", "hana-mode", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://dynamic.zacdn.com/VzJjAqwhTwgdiF2TzHBdNyD4opY=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/c2-outfitters-7121-3480774-1.jpg",
    description:
      "Tailored Wide Pants dari Cloud Nine dirancang dengan bahan terbaik. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk dipakai sehari hari. Jaminan belanja 100% sama dengan gambar.",
    material: "Satin",
  },
  {
    name: "Minimal Knit Top",
    brand: "Mika Select",
    category: "Clothing",
    gender: "Women",
    price: 479000,
    originalPrice: 479000,
    stock: 59,
    rating: 4.3,
    soldCount: 651,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Grey", "White"],
    tags: ["clothing", "mika-select", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/D7hBKeHFCaQE7BdatEr1leuKUNQ=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/minimal-6132-4323335-2.jpg",
    description:
      "Minimal Knit Top dari Mika Select dirancang dengan bahan terbaik. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk dipakai sehari hari. Jaminan belanja 100% sama dengan gambar.",
    material: "Viscose",
  },
  {
    name: "Pleated Midi Skirt",
    brand: "Aria Goods",
    category: "Clothing",
    gender: "Women",
    price: 249000,
    originalPrice: 287000,
    stock: 38,
    rating: 4.8,
    soldCount: 1896,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "White", "Navy"],
    tags: ["clothing", "aria-goods", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/2N_M12PGGCUVd4QeApCuU02v8GA=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/beyounique-4890-1737063-1.jpg",
    description:
      "Minimal Knit Top dari Mika Select dirancang dengan bahan terbaik. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk dipakai sehari hari. Jaminan belanja 100% sama dengan gambar.",

    material: "Satin",
  },
  {
    name: "Satin Slip Dress",
    brand: "Nova Wear",
    category: "Clothing",
    gender: "Women",
    price: 499000,
    originalPrice: 749000,
    stock: 78,
    rating: 4.2,
    soldCount: 299,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Taupe", "Brown"],
    tags: ["clothing", "nova-wear", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/PlF7vKkdp4WaEdScBj6-wF6X1Vs=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/trendyol-1715-9011684-1.jpg",
    description:
      "Satin Slip Dress dari Nova Wear dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Linen Blend",
  },
  {
    name: "Classic Denim Jacket",
    brand: "Eunoia",
    category: "Clothing",
    gender: "Men",
    price: 249000,
    originalPrice: 312000,
    stock: 86,
    rating: 4.8,
    soldCount: 681,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Beige", "Taupe"],
    tags: ["clothing", "eunoia", "men", "new-arrival", "daily"],
    imageUrl:
      "https://dynamic.zacdn.com/XKMFCaDYxGLTmOqeCNxyNJJ-yXQ=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/2nd-red-5454-1377671-1.jpg",
    description:
      "Classic Denim Jacket dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Blend",
  },
  {
    name: "Essential Crew Neck Tee",
    brand: "Aster & Co",
    category: "Clothing",
    gender: "All",
    price: 339000,
    originalPrice: 458000,
    stock: 25,
    rating: 4.5,
    soldCount: 1120,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "Taupe", "Grey"],
    tags: ["clothing", "aster-&-co", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/DTRDHTJNkGWAoSqVWU6HH_rgyzM=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/giordano-7079-7368825-3.jpg",
    description:
      "Essential Crew Neck Tee dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Linen Blend",
  },
  {
    name: "Utility Cargo Pants",
    brand: "Cloud Nine",
    category: "Clothing",
    gender: "Men",
    price: 169000,
    originalPrice: 195000,
    stock: 13,
    rating: 4.2,
    soldCount: 2338,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Taupe", "Rose"],
    tags: ["clothing", "cloud-nine", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://dynamic.zacdn.com/__wzs5wprJdlKaG_yELXKOEVeME=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/used-9694-9190135-1.jpg",
    description:
      "Utility Cargo Pants dari Cloud Nine dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Viscose",
  },
  {
    name: "Boxy Crop Shirt",
    brand: "Aster & Co",
    category: "Clothing",
    gender: "Women",
    price: 309000,
    originalPrice: 356000,
    stock: 100,
    rating: 4.6,
    soldCount: 1091,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Beige", "Navy", "Sage"],
    tags: ["clothing", "aster-&-co", "women", "new-arrival", "daily"],
    imageUrl:
      "https://dynamic.zacdn.com/GYcaWSkuNIw2NluDwQ_4UZwpd8A=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/c2-outfitters-7350-2277725-5.jpg",
    description:
      "Boxy Crop Shirt dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Linen Blend",
  },
  {
    name: "Everyday Chino Shorts",
    brand: "Nara Studio",
    category: "Clothing",
    gender: "Men",
    price: 299000,
    originalPrice: 404000,
    stock: 101,
    rating: 4.0,
    soldCount: 464,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Cream", "Beige", "Navy"],
    tags: ["clothing", "nara-studio", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/WcUmme_263NmVmxr18cjJbIPb6w=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/marks-spencer-0090-4500325-1.jpg",
    description:
      "Everyday Chino Shorts dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Viscose",
  },
  {
    name: "Soft Ribbed Jumper",
    brand: "Hana Mode",
    category: "Clothing",
    gender: "Men",
    price: 609000,
    originalPrice: 823000,
    stock: 37,
    rating: 5.0,
    soldCount: 62,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["White", "Sage", "Brown"],
    tags: ["clothing", "hana-mode", "men", "new-arrival", "daily"],
    imageUrl:
      "https://dynamic.zacdn.com/H2gN8cDQ9FjMdT9Qw8cuSTCLR4c=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/marks-spencer-1973-8552725-1.jpg",
    description:
      "Soft Ribbed Jumper dari Hana Mode dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Blend",
  },
  {
    name: "Poplin Oversized Shirt",
    brand: "Eunoia",
    category: "Clothing",
    gender: "Women",
    price: 499000,
    originalPrice: 624000,
    stock: 5,
    rating: 5.0,
    soldCount: 2962,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Brown", "Sage", "Cream"],
    tags: ["clothing", "eunoia", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=900&auto=format&fit=crop",
    description:
      "Poplin Oversized Shirt dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "High Waist Straight Jeans",
    brand: "Velvet Lane",
    category: "Clothing",
    gender: "Women",
    price: 769000,
    originalPrice: 1039000,
    stock: 52,
    rating: 4.8,
    soldCount: 2224,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "Black", "Grey"],
    tags: ["clothing", "velvet-lane", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=900&auto=format&fit=crop",
    description:
      "High Waist Straight Jeans dari Velvet Lane dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Blend",
  },
  {
    name: "Textured Mini Dress",
    brand: "Aster & Co",
    category: "Clothing",
    gender: "Women",
    price: 269000,
    originalPrice: 310000,
    stock: 12,
    rating: 4.2,
    soldCount: 2338,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["White", "Beige", "Rose"],
    tags: ["clothing", "aster-&-co", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?q=80&w=900&auto=format&fit=crop",
    description:
      "Textured Mini Dress dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Satin",
  },
  {
    name: "Cotton Wrap Blouse",
    brand: "Dara Daily",
    category: "Clothing",
    gender: "All",
    price: 289000,
    originalPrice: 289000,
    stock: 75,
    rating: 4.2,
    soldCount: 2176,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Beige", "Navy", "Taupe"],
    tags: ["clothing", "dara-daily", "all", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=900&auto=format&fit=crop",
    description:
      "Cotton Wrap Blouse dari Dara Daily dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Court Low Sneakers",
    brand: "Nova Wear",
    category: "Shoes",
    gender: "All",
    price: 1219000,
    originalPrice: 1829000,
    stock: 61,
    rating: 4.9,
    soldCount: 1864,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["White", "Taupe", "Sage"],
    tags: ["shoes", "nova-wear", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=900&auto=format&fit=crop",
    description:
      "Court Low Sneakers dari Nova Wear dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Classic Leather Loafers",
    brand: "Aster & Co",
    category: "Shoes",
    gender: "All",
    price: 249000,
    originalPrice: 337000,
    stock: 80,
    rating: 4.2,
    soldCount: 305,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Black", "Taupe", "White"],
    tags: ["shoes", "aster-&-co", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=900&auto=format&fit=crop",
    description:
      "Classic Leather Loafers dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Strappy Block Heels",
    brand: "Cloud Nine",
    category: "Shoes",
    gender: "Women",
    price: 379000,
    originalPrice: 512000,
    stock: 90,
    rating: 4.5,
    soldCount: 2223,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Cream", "Rose", "Taupe"],
    tags: ["shoes", "cloud-nine", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=900&auto=format&fit=crop",
    description:
      "Strappy Block Heels dari Cloud Nine dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Knit Upper",
  },
  {
    name: "Daily Runner Shoes",
    brand: "Trove",
    category: "Shoes",
    gender: "Women",
    price: 679000,
    originalPrice: 679000,
    stock: 60,
    rating: 4.4,
    soldCount: 1698,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Rose", "Black", "White"],
    tags: ["shoes", "trove", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=900&auto=format&fit=crop",
    description:
      "Daily Runner Shoes dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Knit Upper",
  },
  {
    name: "Minimal Flat Sandals",
    brand: "Luna Atelier",
    category: "Shoes",
    gender: "Women",
    price: 1059000,
    originalPrice: 1059000,
    stock: 29,
    rating: 4.5,
    soldCount: 589,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Navy", "Cream", "Brown"],
    tags: ["shoes", "luna-atelier", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=900&auto=format&fit=crop",
    description:
      "Minimal Flat Sandals dari Luna Atelier dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Canvas",
  },
  {
    name: "Chunky Platform Sneakers",
    brand: "Urban Thread",
    category: "Shoes",
    gender: "All",
    price: 389000,
    originalPrice: 487000,
    stock: 11,
    rating: 4.7,
    soldCount: 2229,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Black", "White", "Taupe"],
    tags: ["shoes", "urban-thread", "all", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=900&auto=format&fit=crop",
    description:
      "Chunky Platform Sneakers dari Urban Thread dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Knit Upper",
  },
  {
    name: "Pointed Ballet Flats",
    brand: "Sora Studio",
    category: "Shoes",
    gender: "Women",
    price: 1439000,
    originalPrice: 1799000,
    stock: 120,
    rating: 4.1,
    soldCount: 1567,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Black", "Navy", "Brown"],
    tags: ["shoes", "sora-studio", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=900&auto=format&fit=crop",
    description:
      "Pointed Ballet Flats dari Sora Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Urban Chelsea Boots",
    brand: "Luxe & Co",
    category: "Shoes",
    gender: "All",
    price: 1279000,
    originalPrice: 1919000,
    stock: 89,
    rating: 4.7,
    soldCount: 649,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Taupe", "Brown", "Beige"],
    tags: ["shoes", "luxe-&-co", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=900&auto=format&fit=crop",
    description:
      "Urban Chelsea Boots dari Luxe & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Leather",
  },
  {
    name: "Soft Slide Sandals",
    brand: "Zalora Edit",
    category: "Shoes",
    gender: "Men",
    price: 349000,
    originalPrice: 524000,
    stock: 11,
    rating: 4.6,
    soldCount: 2074,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Sage", "Cream", "Black"],
    tags: ["shoes", "zalora-edit", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Slide Sandals dari Zalora Edit dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Canvas",
  },
  {
    name: "Retro Trainer Sneakers",
    brand: "Trove",
    category: "Shoes",
    gender: "Women",
    price: 369000,
    originalPrice: 499000,
    stock: 115,
    rating: 4.2,
    soldCount: 506,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Beige", "Taupe", "Black"],
    tags: ["shoes", "trove", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=900&auto=format&fit=crop",
    description:
      "Retro Trainer Sneakers dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Knit Upper",
  },
  {
    name: "Canvas Slip On",
    brand: "Trove",
    category: "Shoes",
    gender: "Women",
    price: 999000,
    originalPrice: 1149000,
    stock: 96,
    rating: 4.3,
    soldCount: 1102,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Navy", "Cream", "Brown"],
    tags: ["shoes", "trove", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=900&auto=format&fit=crop",
    description:
      "Canvas Slip On dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Formal Oxford Shoes",
    brand: "Aria Goods",
    category: "Shoes",
    gender: "Men",
    price: 379000,
    originalPrice: 379000,
    stock: 77,
    rating: 5.0,
    soldCount: 315,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Sage", "Taupe", "Brown"],
    tags: ["shoes", "aria-goods", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=900&auto=format&fit=crop",
    description:
      "Formal Oxford Shoes dari Aria Goods dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Minimal Mule Sandals",
    brand: "Rumi Basics",
    category: "Shoes",
    gender: "Men",
    price: 369000,
    originalPrice: 369000,
    stock: 25,
    rating: 4.4,
    soldCount: 2240,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Brown", "Sage", "Black"],
    tags: ["shoes", "rumi-basics", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=900&auto=format&fit=crop",
    description:
      "Minimal Mule Sandals dari Rumi Basics dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Synthetic Leather",
  },
  {
    name: "Sporty Lace Up Shoes",
    brand: "Urban Thread",
    category: "Shoes",
    gender: "Women",
    price: 539000,
    originalPrice: 620000,
    stock: 100,
    rating: 4.6,
    soldCount: 1130,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Brown", "Taupe", "Grey"],
    tags: ["shoes", "urban-thread", "women", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=900&auto=format&fit=crop",
    description:
      "Sporty Lace Up Shoes dari Urban Thread dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Comfort Walking Sneakers",
    brand: "Zalora Edit",
    category: "Shoes",
    gender: "Men",
    price: 1489000,
    originalPrice: 1862000,
    stock: 16,
    rating: 4.6,
    soldCount: 1148,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    colors: ["Black", "Beige", "Grey"],
    tags: ["shoes", "zalora-edit", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=900&auto=format&fit=crop",
    description:
      "Comfort Walking Sneakers dari Zalora Edit dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rubber Sole",
  },
  {
    name: "Structured Tote Bag",
    brand: "Luxe & Co",
    category: "Bags",
    gender: "Men",
    price: 359000,
    originalPrice: 539000,
    stock: 95,
    rating: 4.4,
    soldCount: 54,
    sizes: ["All Size"],
    colors: ["White", "Beige", "Cream"],
    tags: ["bags", "luxe-&-co", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=900&auto=format&fit=crop",
    description:
      "Structured Tote Bag dari Luxe & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Mini Crossbody Bag",
    brand: "Mave Official",
    category: "Bags",
    gender: "Women",
    price: 899000,
    originalPrice: 1214000,
    stock: 21,
    rating: 4.0,
    soldCount: 1508,
    sizes: ["All Size"],
    colors: ["Black", "Grey", "Taupe"],
    tags: ["bags", "mave-official", "women", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=900&auto=format&fit=crop",
    description:
      "Mini Crossbody Bag dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Leather",
  },
  {
    name: "Soft Shoulder Bag",
    brand: "Aria Goods",
    category: "Bags",
    gender: "Men",
    price: 609000,
    originalPrice: 823000,
    stock: 100,
    rating: 4.2,
    soldCount: 984,
    sizes: ["All Size"],
    colors: ["Cream", "Beige", "Navy"],
    tags: ["bags", "aria-goods", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1590739225289-bd31519780c3?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Shoulder Bag dari Aria Goods dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Canvas",
  },
  {
    name: "Everyday Backpack",
    brand: "Trove",
    category: "Bags",
    gender: "Men",
    price: 1099000,
    originalPrice: 1264000,
    stock: 115,
    rating: 4.7,
    soldCount: 1031,
    sizes: ["All Size"],
    colors: ["Brown", "Cream", "White"],
    tags: ["bags", "trove", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1606522754091-a3bbf9ad4cb3?q=80&w=900&auto=format&fit=crop",
    description:
      "Everyday Backpack dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Leather",
  },
  {
    name: "Quilted Chain Bag",
    brand: "Eunoia",
    category: "Bags",
    gender: "Women",
    price: 759000,
    originalPrice: 759000,
    stock: 49,
    rating: 4.3,
    soldCount: 947,
    sizes: ["All Size"],
    colors: ["Taupe", "Black", "Beige"],
    tags: ["bags", "eunoia", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    description:
      "Quilted Chain Bag dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Canvas Shopper Bag",
    brand: "Nova Wear",
    category: "Bags",
    gender: "Men",
    price: 509000,
    originalPrice: 509000,
    stock: 87,
    rating: 4.5,
    soldCount: 2798,
    sizes: ["All Size"],
    colors: ["Sage", "Grey", "Black"],
    tags: ["bags", "nova-wear", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=900&auto=format&fit=crop",
    description:
      "Canvas Shopper Bag dari Nova Wear dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Compact Sling Bag",
    brand: "Zalora Edit",
    category: "Bags",
    gender: "Men",
    price: 379000,
    originalPrice: 512000,
    stock: 18,
    rating: 4.6,
    soldCount: 1430,
    sizes: ["All Size"],
    colors: ["Grey", "Navy", "White"],
    tags: ["bags", "zalora-edit", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=900&auto=format&fit=crop",
    description:
      "Compact Sling Bag dari Zalora Edit dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Office Laptop Tote",
    brand: "Mika Select",
    category: "Bags",
    gender: "Women",
    price: 399000,
    originalPrice: 459000,
    stock: 60,
    rating: 4.0,
    soldCount: 2220,
    sizes: ["All Size"],
    colors: ["Taupe", "Grey", "Navy"],
    tags: ["bags", "mika-select", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1590739225289-bd31519780c3?q=80&w=900&auto=format&fit=crop",
    description:
      "Office Laptop Tote dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Classic Bucket Bag",
    brand: "Urban Thread",
    category: "Bags",
    gender: "All",
    price: 949000,
    originalPrice: 1092000,
    stock: 97,
    rating: 4.9,
    soldCount: 2092,
    sizes: ["All Size"],
    colors: ["Brown", "Navy", "Grey"],
    tags: ["bags", "urban-thread", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1606522754091-a3bbf9ad4cb3?q=80&w=900&auto=format&fit=crop",
    description:
      "Classic Bucket Bag dari Urban Thread dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Textured Clutch Bag",
    brand: "Mave Official",
    category: "Bags",
    gender: "Women",
    price: 859000,
    originalPrice: 859000,
    stock: 90,
    rating: 4.9,
    soldCount: 2789,
    sizes: ["All Size"],
    colors: ["Cream", "Brown", "Navy"],
    tags: ["bags", "mave-official", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    description:
      "Textured Clutch Bag dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon",
  },
  {
    name: "Minimal Belt Bag",
    brand: "Bumi Atelier",
    category: "Bags",
    gender: "Men",
    price: 519000,
    originalPrice: 519000,
    stock: 82,
    rating: 4.7,
    soldCount: 1919,
    sizes: ["All Size"],
    colors: ["Rose", "Beige", "Taupe"],
    tags: ["bags", "bumi-atelier", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=900&auto=format&fit=crop",
    description:
      "Minimal Belt Bag dari Bumi Atelier dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Canvas",
  },
  {
    name: "Soft Hobo Bag",
    brand: "Hana Mode",
    category: "Bags",
    gender: "Men",
    price: 999000,
    originalPrice: 999000,
    stock: 89,
    rating: 4.6,
    soldCount: 1387,
    sizes: ["All Size"],
    colors: ["White", "Taupe", "Brown"],
    tags: ["bags", "hana-mode", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Hobo Bag dari Hana Mode dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Canvas",
  },
  {
    name: "Gold Hoop Earrings",
    brand: "Aster & Co",
    category: "Accessories",
    gender: "Women",
    price: 139000,
    originalPrice: 139000,
    stock: 65,
    rating: 4.6,
    soldCount: 313,
    sizes: ["All Size"],
    colors: ["Rose", "Navy", "Taupe"],
    tags: ["accessories", "aster-&-co", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=900&auto=format&fit=crop",
    description:
      "Gold Hoop Earrings dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Silk Blend",
  },
  {
    name: "Layered Necklace Set",
    brand: "Noir Avenue",
    category: "Accessories",
    gender: "Women",
    price: 299000,
    originalPrice: 299000,
    stock: 93,
    rating: 4.0,
    soldCount: 451,
    sizes: ["All Size"],
    colors: ["Navy", "Taupe", "Cream"],
    tags: ["accessories", "noir-avenue", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1506629905607-d9f297d41c20?q=80&w=900&auto=format&fit=crop",
    description:
      "Layered Necklace Set dari Noir Avenue dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Metal Alloy",
  },
  {
    name: "Silk Square Scarf",
    brand: "Eunoia",
    category: "Accessories",
    gender: "Women",
    price: 399000,
    originalPrice: 399000,
    stock: 22,
    rating: 4.8,
    soldCount: 2749,
    sizes: ["All Size"],
    colors: ["Sage", "Beige", "Grey"],
    tags: ["accessories", "eunoia", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=900&auto=format&fit=crop",
    description:
      "Silk Square Scarf dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Stainless Steel",
  },
  {
    name: "Minimal Leather Belt",
    brand: "Mave Official",
    category: "Accessories",
    gender: "All",
    price: 569000,
    originalPrice: 854000,
    stock: 111,
    rating: 4.9,
    soldCount: 1841,
    sizes: ["All Size"],
    colors: ["Cream", "Rose", "Sage"],
    tags: ["accessories", "mave-official", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=900&auto=format&fit=crop",
    description:
      "Minimal Leather Belt dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Leather",
  },
  {
    name: "Oval Sunglasses",
    brand: "Hana Mode",
    category: "Accessories",
    gender: "Men",
    price: 579000,
    originalPrice: 869000,
    stock: 67,
    rating: 4.6,
    soldCount: 1139,
    sizes: ["All Size"],
    colors: ["Rose", "White", "Brown"],
    tags: ["accessories", "hana-mode", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=900&auto=format&fit=crop",
    description:
      "Oval Sunglasses dari Hana Mode dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Acetate",
  },
  {
    name: "Classic Baseball Cap",
    brand: "Nara Studio",
    category: "Accessories",
    gender: "All",
    price: 259000,
    originalPrice: 298000,
    stock: 22,
    rating: 4.2,
    soldCount: 1583,
    sizes: ["All Size"],
    colors: ["Cream", "Taupe", "White"],
    tags: ["accessories", "nara-studio", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=900&auto=format&fit=crop",
    description:
      "Classic Baseball Cap dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Silk Blend",
  },
  {
    name: "Textured Hair Claw",
    brand: "Mave Official",
    category: "Accessories",
    gender: "Men",
    price: 259000,
    originalPrice: 350000,
    stock: 12,
    rating: 4.2,
    soldCount: 1735,
    sizes: ["All Size"],
    colors: ["Navy", "Black", "Beige"],
    tags: ["accessories", "mave-official", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1506629905607-d9f297d41c20?q=80&w=900&auto=format&fit=crop",
    description:
      "Textured Hair Claw dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Metal Alloy",
  },
  {
    name: "Slim Card Holder",
    brand: "Mave Official",
    category: "Accessories",
    gender: "Men",
    price: 269000,
    originalPrice: 310000,
    stock: 73,
    rating: 4.7,
    soldCount: 2251,
    sizes: ["All Size"],
    colors: ["Beige", "Taupe", "Rose"],
    tags: ["accessories", "mave-official", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=900&auto=format&fit=crop",
    description:
      "Slim Card Holder dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Acetate",
  },
  {
    name: "Elegant Watch",
    brand: "Sora Studio",
    category: "Accessories",
    gender: "Women",
    price: 319000,
    originalPrice: 399000,
    stock: 48,
    rating: 4.7,
    soldCount: 1671,
    sizes: ["All Size"],
    colors: ["Cream", "Rose", "Beige"],
    tags: ["accessories", "sora-studio", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=900&auto=format&fit=crop",
    description:
      "Elegant Watch dari Sora Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Silk Blend",
  },
  {
    name: "Pearl Bracelet",
    brand: "SHAN",
    category: "Accessories",
    gender: "All",
    price: 419000,
    originalPrice: 566000,
    stock: 15,
    rating: 4.6,
    soldCount: 570,
    sizes: ["All Size"],
    colors: ["Rose", "Cream", "Black"],
    tags: ["accessories", "shan", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=900&auto=format&fit=crop",
    description:
      "Pearl Bracelet dari SHAN dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Silk Blend",
  },
  {
    name: "Woven Bucket Hat",
    brand: "Kaira Label",
    category: "Accessories",
    gender: "Men",
    price: 249000,
    originalPrice: 249000,
    stock: 48,
    rating: 4.8,
    soldCount: 1567,
    sizes: ["All Size"],
    colors: ["Brown", "Navy", "Beige"],
    tags: ["accessories", "kaira-label", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=900&auto=format&fit=crop",
    description:
      "Woven Bucket Hat dari Kaira Label dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Silk Blend",
  },
  {
    name: "Minimal Ring Set",
    brand: "Zalora Edit",
    category: "Accessories",
    gender: "All",
    price: 59000,
    originalPrice: 89000,
    stock: 49,
    rating: 4.2,
    soldCount: 296,
    sizes: ["All Size"],
    colors: ["Black", "Beige", "Taupe"],
    tags: ["accessories", "zalora-edit", "all", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1506629905607-d9f297d41c20?q=80&w=900&auto=format&fit=crop",
    description:
      "Minimal Ring Set dari Zalora Edit dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Metal Alloy",
  },
  {
    name: "Hydrating Lip Tint",
    brand: "Velvet Lane",
    category: "Beauty",
    gender: "All",
    price: 429000,
    originalPrice: 429000,
    stock: 65,
    rating: 4.7,
    soldCount: 2325,
    sizes: ["All Size"],
    colors: ["Taupe", "Rose", "Brown"],
    tags: ["beauty", "velvet-lane", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=900&auto=format&fit=crop",
    description:
      "Hydrating Lip Tint dari Velvet Lane dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Formula",
  },
  {
    name: "Soft Matte Cushion",
    brand: "Mika Select",
    category: "Beauty",
    gender: "All",
    price: 419000,
    originalPrice: 566000,
    stock: 19,
    rating: 4.8,
    soldCount: 685,
    sizes: ["All Size"],
    colors: ["Brown", "White", "Black"],
    tags: ["beauty", "mika-select", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Matte Cushion dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Hydrating Formula",
  },
  {
    name: "Daily Glow Sunscreen",
    brand: "Nara Studio",
    category: "Beauty",
    gender: "All",
    price: 289000,
    originalPrice: 434000,
    stock: 80,
    rating: 4.7,
    soldCount: 2584,
    sizes: ["All Size"],
    colors: ["Taupe", "White", "Brown"],
    tags: ["beauty", "nara-studio", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=900&auto=format&fit=crop",
    description:
      "Daily Glow Sunscreen dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dermatologically Tested Formula",
  },
  {
    name: "Clean Girl Blush",
    brand: "Trove",
    category: "Beauty",
    gender: "Women",
    price: 259000,
    originalPrice: 350000,
    stock: 52,
    rating: 4.1,
    soldCount: 2667,
    sizes: ["All Size"],
    colors: ["Grey", "Black", "Navy"],
    tags: ["beauty", "trove", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=900&auto=format&fit=crop",
    description:
      "Clean Girl Blush dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dermatologically Tested Formula",
  },
  {
    name: "Nude Eyeshadow Palette",
    brand: "Eunoia",
    category: "Beauty",
    gender: "All",
    price: 309000,
    originalPrice: 356000,
    stock: 95,
    rating: 4.2,
    soldCount: 736,
    sizes: ["All Size"],
    colors: ["Sage", "Brown", "Rose"],
    tags: ["beauty", "eunoia", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=900&auto=format&fit=crop",
    description:
      "Nude Eyeshadow Palette dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Hydrating Formula",
  },
  {
    name: "Fresh Mist Toner",
    brand: "Aster & Co",
    category: "Beauty",
    gender: "Women",
    price: 409000,
    originalPrice: 471000,
    stock: 111,
    rating: 4.9,
    soldCount: 1157,
    sizes: ["All Size"],
    colors: ["Rose", "Taupe", "Beige"],
    tags: ["beauty", "aster-&-co", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=900&auto=format&fit=crop",
    description:
      "Fresh Mist Toner dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Lightweight Formula",
  },
  {
    name: "Velvet Lip Cream",
    brand: "Maison Daily",
    category: "Beauty",
    gender: "Women",
    price: 49000,
    originalPrice: 62000,
    stock: 67,
    rating: 4.2,
    soldCount: 1073,
    sizes: ["All Size"],
    colors: ["Grey", "Brown", "Sage"],
    tags: ["beauty", "maison-daily", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=900&auto=format&fit=crop",
    description:
      "Velvet Lip Cream dari Maison Daily dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Formula",
  },
  {
    name: "Gentle Cleansing Balm",
    brand: "Mave Official",
    category: "Beauty",
    gender: "All",
    price: 89000,
    originalPrice: 89000,
    stock: 67,
    rating: 4.6,
    soldCount: 999,
    sizes: ["All Size"],
    colors: ["Rose", "Beige", "Sage"],
    tags: ["beauty", "mave-official", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=900&auto=format&fit=crop",
    description:
      "Gentle Cleansing Balm dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dermatologically Tested Formula",
  },
  {
    name: "Brow Defining Pencil",
    brand: "Mika Select",
    category: "Beauty",
    gender: "Women",
    price: 219000,
    originalPrice: 219000,
    stock: 36,
    rating: 4.3,
    soldCount: 2397,
    sizes: ["All Size"],
    colors: ["Grey", "Rose", "Beige"],
    tags: ["beauty", "mika-select", "women", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=900&auto=format&fit=crop",
    description:
      "Brow Defining Pencil dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Lightweight Formula",
  },
  {
    name: "Long Wear Mascara",
    brand: "Cloud Nine",
    category: "Beauty",
    gender: "Women",
    price: 259000,
    originalPrice: 389000,
    stock: 44,
    rating: 4.3,
    soldCount: 509,
    sizes: ["All Size"],
    colors: ["Taupe", "Grey", "White"],
    tags: ["beauty", "cloud-nine", "women", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=900&auto=format&fit=crop",
    description:
      "Long Wear Mascara dari Cloud Nine dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Formula",
  },
  {
    name: "Skin Barrier Moisturizer",
    brand: "Cloud Nine",
    category: "Beauty",
    gender: "Women",
    price: 169000,
    originalPrice: 254000,
    stock: 97,
    rating: 4.6,
    soldCount: 2163,
    sizes: ["All Size"],
    colors: ["Beige", "Brown", "White"],
    tags: ["beauty", "cloud-nine", "women", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=900&auto=format&fit=crop",
    description:
      "Skin Barrier Moisturizer dari Cloud Nine dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Lightweight Formula",
  },
  {
    name: "Soft Glow Highlighter",
    brand: "Rumi Basics",
    category: "Beauty",
    gender: "All",
    price: 179000,
    originalPrice: 206000,
    stock: 6,
    rating: 4.7,
    soldCount: 533,
    sizes: ["All Size"],
    colors: ["Brown", "Black", "Sage"],
    tags: ["beauty", "rumi-basics", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Glow Highlighter dari Rumi Basics dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Vegan Formula",
  },
  {
    name: "Oversized Cotton Blazer",
    brand: "Bumi Atelier",
    category: "Outerwear",
    gender: "Women",
    price: 1499000,
    originalPrice: 1499000,
    stock: 41,
    rating: 4.5,
    soldCount: 1819,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Cream", "Black"],
    tags: ["outerwear", "bumi-atelier", "women", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=900&auto=format&fit=crop",
    description:
      "Oversized Cotton Blazer dari Bumi Atelier dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Cropped Trench Jacket",
    brand: "Dara Daily",
    category: "Outerwear",
    gender: "Men",
    price: 539000,
    originalPrice: 539000,
    stock: 14,
    rating: 4.6,
    soldCount: 2826,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Cream", "Sage"],
    tags: ["outerwear", "dara-daily", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1520975954732-35dd22299614?q=80&w=900&auto=format&fit=crop",
    description:
      "Cropped Trench Jacket dari Dara Daily dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Twill",
  },
  {
    name: "Lightweight Bomber Jacket",
    brand: "Mave Official",
    category: "Outerwear",
    gender: "All",
    price: 879000,
    originalPrice: 879000,
    stock: 82,
    rating: 4.6,
    soldCount: 2548,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Sage", "Navy"],
    tags: ["outerwear", "mave-official", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=900&auto=format&fit=crop",
    description:
      "Lightweight Bomber Jacket dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Wool Blend Coat",
    brand: "Rumi Basics",
    category: "Outerwear",
    gender: "Men",
    price: 1009000,
    originalPrice: 1363000,
    stock: 77,
    rating: 4.6,
    soldCount: 2512,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["White", "Taupe", "Sage"],
    tags: ["outerwear", "rumi-basics", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1523398002811-999ca8dec234?q=80&w=900&auto=format&fit=crop",
    description:
      "Wool Blend Coat dari Rumi Basics dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Twill",
  },
  {
    name: "Denim Overshirt",
    brand: "Luxe & Co",
    category: "Outerwear",
    gender: "Women",
    price: 649000,
    originalPrice: 649000,
    stock: 14,
    rating: 4.2,
    soldCount: 1688,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Rose", "Beige", "Brown"],
    tags: ["outerwear", "luxe-&-co", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1543076447-215ad9ba6923?q=80&w=900&auto=format&fit=crop",
    description:
      "Denim Overshirt dari Luxe & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Wool Blend",
  },
  {
    name: "Padded Utility Vest",
    brand: "Mika Select",
    category: "Outerwear",
    gender: "Men",
    price: 979000,
    originalPrice: 1469000,
    stock: 115,
    rating: 4.5,
    soldCount: 2830,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Brown", "Beige"],
    tags: ["outerwear", "mika-select", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=900&auto=format&fit=crop",
    description:
      "Padded Utility Vest dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Twill",
  },
  {
    name: "Relaxed Cardigan Jacket",
    brand: "Velvet Lane",
    category: "Outerwear",
    gender: "All",
    price: 1639000,
    originalPrice: 1639000,
    stock: 39,
    rating: 4.8,
    soldCount: 307,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Cream", "Brown"],
    tags: ["outerwear", "velvet-lane", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1520975954732-35dd22299614?q=80&w=900&auto=format&fit=crop",
    description:
      "Relaxed Cardigan Jacket dari Velvet Lane dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Longline Coat",
    brand: "Rumi Basics",
    category: "Outerwear",
    gender: "All",
    price: 559000,
    originalPrice: 699000,
    stock: 94,
    rating: 4.4,
    soldCount: 1130,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "Beige", "Rose"],
    tags: ["outerwear", "rumi-basics", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=900&auto=format&fit=crop",
    description:
      "Longline Coat dari Rumi Basics dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Twill",
  },
  {
    name: "Classic Field Jacket",
    brand: "Thread Theory",
    category: "Outerwear",
    gender: "Men",
    price: 1779000,
    originalPrice: 1779000,
    stock: 46,
    rating: 4.6,
    soldCount: 120,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["White", "Taupe", "Black"],
    tags: ["outerwear", "thread-theory", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1523398002811-999ca8dec234?q=80&w=900&auto=format&fit=crop",
    description:
      "Classic Field Jacket dari Thread Theory dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Knit",
  },
  {
    name: "Soft Knit Outer",
    brand: "Hana Mode",
    category: "Outerwear",
    gender: "Men",
    price: 349000,
    originalPrice: 349000,
    stock: 88,
    rating: 4.4,
    soldCount: 1154,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Cream", "Navy", "Rose"],
    tags: ["outerwear", "hana-mode", "men", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1543076447-215ad9ba6923?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Knit Outer dari Hana Mode dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Premium Voal Hijab",
    brand: "Kaira Label",
    category: "Modest Wear",
    gender: "Men",
    price: 519000,
    originalPrice: 649000,
    stock: 90,
    rating: 4.1,
    soldCount: 673,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Navy", "Rose"],
    tags: ["modest-wear", "kaira-label", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1622445275576-721325763afe?q=80&w=900&auto=format&fit=crop",
    description:
      "Premium Voal Hijab dari Kaira Label dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "Longline Tunic Set",
    brand: "Nara Studio",
    category: "Modest Wear",
    gender: "Men",
    price: 779000,
    originalPrice: 779000,
    stock: 45,
    rating: 4.3,
    soldCount: 489,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Navy", "Sage", "Black"],
    tags: ["modest-wear", "nara-studio", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?q=80&w=900&auto=format&fit=crop",
    description:
      "Longline Tunic Set dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Polyester",
  },
  {
    name: "A-Line Modest Dress",
    brand: "Nova Wear",
    category: "Modest Wear",
    gender: "All",
    price: 139000,
    originalPrice: 139000,
    stock: 84,
    rating: 4.8,
    soldCount: 2576,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Rose", "Black", "Taupe"],
    tags: ["modest-wear", "nova-wear", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1603217041431-9a99375be271?q=80&w=900&auto=format&fit=crop",
    description:
      "A-Line Modest Dress dari Nova Wear dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Ceruty",
  },
  {
    name: "Pleated Abaya Dress",
    brand: "Mika Select",
    category: "Modest Wear",
    gender: "Men",
    price: 239000,
    originalPrice: 275000,
    stock: 67,
    rating: 4.1,
    soldCount: 2595,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Beige", "Taupe", "Cream"],
    tags: ["modest-wear", "mika-select", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1612722432474-b971cdcea546?q=80&w=900&auto=format&fit=crop",
    description:
      "Pleated Abaya Dress dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Ceruty",
  },
  {
    name: "Soft Inner Hijab",
    brand: "Nara Studio",
    category: "Modest Wear",
    gender: "Men",
    price: 89000,
    originalPrice: 121000,
    stock: 33,
    rating: 5.0,
    soldCount: 479,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Rose", "White", "Cream"],
    tags: ["modest-wear", "nara-studio", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=900&auto=format&fit=crop",
    description:
      "Soft Inner Hijab dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Blend",
  },
  {
    name: "Loose Palazzo Pants",
    brand: "Mave Official",
    category: "Modest Wear",
    gender: "Men",
    price: 729000,
    originalPrice: 1094000,
    stock: 111,
    rating: 4.5,
    soldCount: 1949,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Rose", "Cream"],
    tags: ["modest-wear", "mave-official", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1622445275576-721325763afe?q=80&w=900&auto=format&fit=crop",
    description:
      "Loose Palazzo Pants dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Rayon",
  },
  {
    name: "Layered Maxi Skirt",
    brand: "Velvet Lane",
    category: "Modest Wear",
    gender: "All",
    price: 839000,
    originalPrice: 1133000,
    stock: 115,
    rating: 4.1,
    soldCount: 1714,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Sage", "Brown"],
    tags: ["modest-wear", "velvet-lane", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?q=80&w=900&auto=format&fit=crop",
    description:
      "Layered Maxi Skirt dari Velvet Lane dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Cotton Blend",
  },
  {
    name: "Everyday Prayer Set",
    brand: "Trove",
    category: "Modest Wear",
    gender: "All",
    price: 459000,
    originalPrice: 620000,
    stock: 67,
    rating: 4.9,
    soldCount: 1844,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Sage", "Rose", "Grey"],
    tags: ["modest-wear", "trove", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1603217041431-9a99375be271?q=80&w=900&auto=format&fit=crop",
    description:
      "Everyday Prayer Set dari Trove dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Ceruty",
  },
  {
    name: "Button Modest Shirt",
    brand: "Kaira Label",
    category: "Modest Wear",
    gender: "Men",
    price: 769000,
    originalPrice: 962000,
    stock: 116,
    rating: 4.2,
    soldCount: 2871,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Navy", "Beige"],
    tags: ["modest-wear", "kaira-label", "men", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1612722432474-b971cdcea546?q=80&w=900&auto=format&fit=crop",
    description:
      "Button Modest Shirt dari Kaira Label dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Voal",
  },
  {
    name: "Simple Kaftan Dress",
    brand: "Mika Select",
    category: "Modest Wear",
    gender: "Men",
    price: 479000,
    originalPrice: 719000,
    stock: 108,
    rating: 4.4,
    soldCount: 2733,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Cream", "Rose", "Black"],
    tags: ["modest-wear", "mika-select", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=900&auto=format&fit=crop",
    description:
      "Simple Kaftan Dress dari Mika Select dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Ceruty",
  },
  {
    name: "Flex Training Leggings",
    brand: "Eunoia",
    category: "Sportswear",
    gender: "Women",
    price: 849000,
    originalPrice: 977000,
    stock: 17,
    rating: 4.5,
    soldCount: 1886,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Cream", "Navy"],
    tags: ["sportswear", "eunoia", "women", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=900&auto=format&fit=crop",
    description:
      "Flex Training Leggings dari Eunoia dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dry Fit Polyester",
  },
  {
    name: "Dry Fit Training Tee",
    brand: "Aria Goods",
    category: "Sportswear",
    gender: "Men",
    price: 699000,
    originalPrice: 804000,
    stock: 93,
    rating: 4.4,
    soldCount: 343,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Grey", "Sage", "Navy"],
    tags: ["sportswear", "aria-goods", "men", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=900&auto=format&fit=crop",
    description:
      "Dry Fit Training Tee dari Aria Goods dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Stretch Fabric",
  },
  {
    name: "Running Windbreaker",
    brand: "Nara Studio",
    category: "Sportswear",
    gender: "All",
    price: 789000,
    originalPrice: 789000,
    stock: 35,
    rating: 4.6,
    soldCount: 1192,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "White", "Navy"],
    tags: ["sportswear", "nara-studio", "all", "new-arrival", "minimal"],
    imageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=900&auto=format&fit=crop",
    description:
      "Running Windbreaker dari Nara Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dry Fit Polyester",
  },
  {
    name: "Sport Bra Medium Support",
    brand: "Rumi Basics",
    category: "Sportswear",
    gender: "All",
    price: 659000,
    originalPrice: 659000,
    stock: 120,
    rating: 4.0,
    soldCount: 1343,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Brown", "Grey"],
    tags: ["sportswear", "rumi-basics", "all", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=900&auto=format&fit=crop",
    description:
      "Sport Bra Medium Support dari Rumi Basics dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Stretch Fabric",
  },
  {
    name: "Lightweight Track Pants",
    brand: "Mave Official",
    category: "Sportswear",
    gender: "All",
    price: 279000,
    originalPrice: 279000,
    stock: 77,
    rating: 4.7,
    soldCount: 752,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Cream", "Beige", "White"],
    tags: ["sportswear", "mave-official", "all", "new-arrival", "editorial"],
    imageUrl:
      "https://images.unsplash.com/photo-1517466787929-bc90951d0974?q=80&w=900&auto=format&fit=crop",
    description:
      "Lightweight Track Pants dari Mave Official dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon Spandex",
  },
  {
    name: "Performance Shorts",
    brand: "Aster & Co",
    category: "Sportswear",
    gender: "Women",
    price: 729000,
    originalPrice: 985000,
    stock: 64,
    rating: 4.6,
    soldCount: 1897,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Brown", "Black", "Rose"],
    tags: ["sportswear", "aster-&-co", "women", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=900&auto=format&fit=crop",
    description:
      "Performance Shorts dari Aster & Co dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Nylon Spandex",
  },
  {
    name: "Yoga Ribbed Tank",
    brand: "Bumi Atelier",
    category: "Sportswear",
    gender: "Men",
    price: 189000,
    originalPrice: 237000,
    stock: 43,
    rating: 4.6,
    soldCount: 1752,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Brown", "Rose", "Beige"],
    tags: ["sportswear", "bumi-atelier", "men", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=900&auto=format&fit=crop",
    description:
      "Yoga Ribbed Tank dari Bumi Atelier dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Stretch Fabric",
  },
  {
    name: "Athletic Hoodie",
    brand: "Sora Studio",
    category: "Sportswear",
    gender: "Women",
    price: 709000,
    originalPrice: 709000,
    stock: 78,
    rating: 4.4,
    soldCount: 1226,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Brown", "Black", "Navy"],
    tags: ["sportswear", "sora-studio", "women", "new-arrival", "daily"],
    imageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=900&auto=format&fit=crop",
    description:
      "Athletic Hoodie dari Sora Studio dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Dry Fit Polyester",
  },
  {
    name: "Training Jogger Pants",
    brand: "Zalora Edit",
    category: "Sportswear",
    gender: "All",
    price: 819000,
    originalPrice: 1229000,
    stock: 82,
    rating: 4.7,
    soldCount: 1187,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Taupe", "Grey", "Beige"],
    tags: ["sportswear", "zalora-edit", "all", "new-arrival", "premium"],
    imageUrl:
      "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=900&auto=format&fit=crop",
    description:
      "Training Jogger Pants dari Zalora Edit dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Breathable Mesh",
  },
  {
    name: "Compression Long Sleeve",
    brand: "Noir Avenue",
    category: "Sportswear",
    gender: "Men",
    price: 269000,
    originalPrice: 404000,
    stock: 87,
    rating: 4.0,
    soldCount: 1820,
    sizes: ["S", "M", "L", "XL", "All Size"],
    colors: ["Black", "Grey", "Cream"],
    tags: ["sportswear", "noir-avenue", "women", "new-arrival", "minimal"],
    imageUrl:
      "https://dynamic.zacdn.com/nb1SDZdaCXN8IXZyfeGA5W3p5UY=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/tiento-1117-9278662-2.jpg",
    description:
      "Compression Long Sleeve dari Noir Avenue dirancang untuk pengalaman belanja fashion modern. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk kebutuhan harian dengan desain simple seperti e-commerce fashion profesional.",
    material: "Breathable Mesh",
  },
];

const seedProducts = async () => {
  try {
    await connectDB();

    await Product.deleteMany();
    await CartItem.deleteMany();
    await WishlistItem.deleteMany();
    await Order.deleteMany();

    const productsWithStandardDescription = products.map((product) => ({
      ...product,
      description: `${product.name} dari ${product.brand} dirancang dengan bahan terbaik. Produk ini memiliki tampilan clean, mudah dipadukan, dan cocok untuk dipakai sehari hari. Jaminan belanja 100% sama dengan gambar.`,
    }));

    const insertedProducts = await Product.insertMany(
      productsWithStandardDescription
    );

    console.log(`Seed success: ${insertedProducts.length} products inserted.`);
    console.log("Cart, wishlist, and orders cleared.");
    process.exit(0);
  } catch (error) {
    console.error(`Seed error: ${error.message}`);
    process.exit(1);
  }
};

seedProducts();

seedProducts();
